# Generated by Django 3.2.6 on 2021-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='delete',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='read',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update',
            field=models.BooleanField(null=True),
        ),
    ]
